openapi: 3.0.1
info:
  description: An API for an easy access to our BigQuery data
  title: NoMagic BigQuery API
  version: 1.0.0
servers:
- url: /
tags:
- description: Parametrized queries saved in our repo
  name: saved_query
paths:
  /v1/data/{saved_query_slug}:
    get:
      description: Retrieve a single saved query result - it works only for not parametrized
        queries
      operationId: get_data
      parameters:
      - description: Slug of the saved query desired to be retrieved
        in: path
        name: saved_query_slug
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResult'
          description: Succesful retrieval of a saved query result
        "400":
          content: {}
          description: Bad request
        "404":
          content: {}
          description: Query not found
        "406":
          content: {}
          description: This query needs parameters to be provided - use POST
      summary: Retrieve a single saved query result
      tags:
      - query_result
      x-openapi-router-controller: openapi_server.controllers.query_result_controller
    post:
      description: Retrieve a single saved query result
      operationId: get_data_with_params
      parameters:
      - description: Slug of a saved query to be executed
        in: path
        name: saved_query_slug
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataRequestBody'
        description: values provided for mapametrized query
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResult'
          description: Succesful retrieval of a saved query result
        "400":
          content: {}
          description: Bad request
        "404":
          content: {}
          description: Query not found
        "406":
          content: {}
          description: This query needs parameters to be provided - use POST
      summary: Retrieve a single saved query result
      tags:
      - query_result
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.query_result_controller
  /v1/saved_queries:
    get:
      description: Retrieves the list of all saved queries
      operationId: list_saved_queries
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SavedQueriesResponse'
          description: Successfully listed
      summary: Retrieves the list of all saved queries
      tags:
      - saved_query
      x-openapi-router-controller: openapi_server.controllers.saved_query_controller
  /v1/saved_queries/{saved_query_slug}:
    get:
      description: Retrieve a single saved query
      operationId: get_saved_query_by_slug
      parameters:
      - description: Slug of the saved query desired to be retrieved
        in: path
        name: saved_query_slug
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SavedQuery'
          description: Succesful retrieval of a saved query
        "400":
          content: {}
          description: Bad request
        "404":
          content: {}
          description: Query not found
      summary: Retrieve a single saved query
      tags:
      - saved_query
      x-openapi-router-controller: openapi_server.controllers.saved_query_controller
components:
  schemas:
    SavedQuery:
      description: An SQL query saved in our repo
      example:
        params:
        - name: evaluation_id
          type: str
        - name: evaluation_id
          type: str
        slug: my-awesome-slug
        sql: SELECT 7;
      properties:
        slug:
          description: Slug of a query (URL-friendly name)
          example: my-awesome-slug
          type: string
        sql:
          description: Query SQL code
          example: SELECT 7;
          type: string
        params:
          description: If query is parametized, here is the list of params used
          items:
            $ref: '#/components/schemas/QueryParam'
          type: array
      required:
      - slug
      - sql
      title: Saved query
      type: object
    QueryParam:
      description: A parameter used in a parametrized query
      example:
        name: evaluation_id
        type: str
      properties:
        name:
          description: name used within a query, snake_case
          example: evaluation_id
          type: string
        type:
          description: type of param, it affects the way it is injected to SQL code
          enum:
          - str
          - int
          type: string
      required:
      - name
      - type
      type: object
    QueryValue:
      description: A value used in a parametrized query, param will be replaced with
        it
      example:
        name: evaluation_id
        value: "7777"
      properties:
        name:
          description: name used within a query, snake_case
          example: evaluation_id
          type: string
        value:
          description: value to be inserted
          example: "7777"
          type: string
      required:
      - name
      - value
      type: object
    DataRequestBody:
      description: data provided in request body when retiving data
      example:
        values:
        - name: evaluation_id
          value: "7777"
        - name: evaluation_id
          value: "7777"
      properties:
        values:
          items:
            $ref: '#/components/schemas/QueryValue'
          type: array
      type: object
    SavedQueriesResponse:
      description: Response object contains all the saved queries
      example:
        saved_queries:
        - params:
          - name: evaluation_id
            type: str
          - name: evaluation_id
            type: str
          slug: my-awesome-slug
          sql: SELECT 7;
        - params:
          - name: evaluation_id
            type: str
          - name: evaluation_id
            type: str
          slug: my-awesome-slug
          sql: SELECT 7;
      properties:
        saved_queries:
          description: List of saved query
          items:
            $ref: '#/components/schemas/SavedQuery'
          type: array
      type: object
    QueryResult:
      description: Query result (data retrieved)
      example:
        executed_sql: SELECT * FROM attempts WHERE evaluation_id=7000;
        data:
        - '{}'
        - '{}'
        error: 'Not Found: Dataset myproject:foo'
      properties:
        executed_sql:
          description: SQL that was executed
          example: SELECT * FROM attempts WHERE evaluation_id=7000;
          type: string
        error:
          description: error message recieved from database
          example: 'Not Found: Dataset myproject:foo'
          type: string
        data:
          items:
            type: object
          type: array
      required:
      - executed_sql
      type: object
