# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class QueryParam(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, type=None):  # noqa: E501
        """QueryParam - a model defined in OpenAPI

        :param name: The name of this QueryParam.  # noqa: E501
        :type name: str
        :param type: The type of this QueryParam.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'name': str,
            'type': str
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type'
        }

        self._name = name
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'QueryParam':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryParam of this QueryParam.  # noqa: E501
        :rtype: QueryParam
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this QueryParam.

        name used within a query, snake_case  # noqa: E501

        :return: The name of this QueryParam.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this QueryParam.

        name used within a query, snake_case  # noqa: E501

        :param name: The name of this QueryParam.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this QueryParam.

        type of param, it affects the way it is injected to SQL code  # noqa: E501

        :return: The type of this QueryParam.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this QueryParam.

        type of param, it affects the way it is injected to SQL code  # noqa: E501

        :param type: The type of this QueryParam.
        :type type: str
        """
        allowed_values = ["str", "int"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type
