# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.saved_query import SavedQuery
from openapi_server import util

from openapi_server.models.saved_query import SavedQuery  # noqa: E501

class SavedQueriesResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, saved_queries=None):  # noqa: E501
        """SavedQueriesResponse - a model defined in OpenAPI

        :param saved_queries: The saved_queries of this SavedQueriesResponse.  # noqa: E501
        :type saved_queries: List[SavedQuery]
        """
        self.openapi_types = {
            'saved_queries': List[SavedQuery]
        }

        self.attribute_map = {
            'saved_queries': 'saved_queries'
        }

        self._saved_queries = saved_queries

    @classmethod
    def from_dict(cls, dikt) -> 'SavedQueriesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SavedQueriesResponse of this SavedQueriesResponse.  # noqa: E501
        :rtype: SavedQueriesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def saved_queries(self):
        """Gets the saved_queries of this SavedQueriesResponse.

        List of saved query  # noqa: E501

        :return: The saved_queries of this SavedQueriesResponse.
        :rtype: List[SavedQuery]
        """
        return self._saved_queries

    @saved_queries.setter
    def saved_queries(self, saved_queries):
        """Sets the saved_queries of this SavedQueriesResponse.

        List of saved query  # noqa: E501

        :param saved_queries: The saved_queries of this SavedQueriesResponse.
        :type saved_queries: List[SavedQuery]
        """

        self._saved_queries = saved_queries
